"""Generate docs/METRICS.md from the metric JSONs the training scripts emit.

Run: python -m scripts.write_metrics_doc

Generated rather than hand-written on purpose: a metrics document that is typed by hand
drifts from the model the moment anything is retrained, and a stale number in a document
titled "honest metrics" is worse than no document.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))

ROOT = Path(__file__).resolve().parents[1]
DOCS = ROOT / "docs"


def pct(v: float, n: int = 1) -> str:
    return f"{v * 100:.{n}f}%"


def main() -> None:
    a = json.loads((DOCS / "metrics_sidea.json").read_text())
    b = json.loads((DOCS / "metrics_sideb.json").read_text())
    f = json.loads((DOCS / "metrics_fusion.json").read_text())
    hb = b["human_baseline"]
    ho = b["held_out"]

    L: list[str] = []
    w = L.append

    w("# AEGIS — Model Metrics\n")
    w("Generated by `scripts/write_metrics_doc.py` from the JSON emitted by the training")
    w("scripts. Do not edit by hand; rerun the generator.\n")

    w("## Read this first\n")
    w("Every figure here comes from **synthetic data**. The transaction ledger was generated")
    w("because no public dataset carries device fingerprints and IPs linked across a customer's")
    w("order history — without which CE 3.0 qualification cannot be computed at all, let alone")
    w("evaluated. Outcome labels were drawn from a documented structural model, so training a")
    w("model to recover them is **partly circular**.\n")
    w("Three things bound that circularity:\n")
    w("1. A per-issuer random effect that is never exposed as a feature to any model.")
    w("2. A deliberately large residual noise term in the outcome draw.")
    w("3. Customer-grouped splits everywhere — no customer appears in two splits.\n")
    w("**These metrics measure whether the pipeline recovers a known structure under noise.**")
    w("They are not external-validity claims. Validation on real dispute data is the next step.\n")
    w("---\n")

    # ---------------- Side B ----------------
    w("## Side B — Inbound evidence forensics\n")
    w(f"Held-out set: **{ho['n']} items**, customers unseen during training.\n")
    w("| Metric | AEGIS | Human baseline |")
    w("|---|---|---|")
    w(f"| Precision | **{pct(ho['precision'])}** | — |")
    w(f"| Recall | **{pct(ho['recall'])}** | {pct(hb['recall'])} |")
    w(f"| F1 | **{pct(ho['f1'])}** | {pct(hb['f1'])} |")
    w(f"| Accuracy | **{pct(ho['accuracy'])}** | {pct(hb['accuracy'])} |")
    w(f"| False-positive rate | **{pct(ho['fpr'])}** | {pct(hb['fpr'])} |")
    w(f"| PR-AUC | {ho['pr_auc']:.3f} | — |")
    w(f"| ROC-AUC | {ho['roc_auc']:.3f} | — |")
    w(f"| Brier | {ho['brier']:.4f} | — |")
    w("")
    c = ho["confusion"]
    w(f"Confusion matrix: TN {c['tn']} · FP {c['fp']} · FN {c['fn']} · TP {c['tp']}\n")
    w(f"Human baseline source: {hb['source']}. That study also found the dominant signal is")
    w("**arithmetic inconsistency**, present in 97.2% of AI-generated receipts and invisible to")
    w("visual inspection — humans have better visual discrimination than most machine")
    w("evaluators and still lose, which is why Side B leads with arithmetic rather than a CNN.\n")

    w("### Per-family recall\n")
    w("An average across families hides which one fails.\n")
    w("| Family | n | Model | Model + rules |")
    w("|---|---|---|---|")
    for fam, r in b["per_family"].items():
        cf = b.get("combined_per_family", {}).get(fam, {})
        if fam == "genuine":
            w(f"| `genuine` (false-positive rate) | {r['n']} | {pct(r['false_positive_rate'])} | "
              f"{pct(cf.get('false_positive_rate', 0))} |")
        else:
            w(f"| `{fam}` | {r['n']} | {pct(r['recall'])} | {pct(cf.get('recall', 0))} |")
    w("")
    w("`recycled` is a genuine, unaltered receipt from a **different real transaction**. No")
    w("pixel-level forensic can flag it — nothing about the image is fake. It is caught only by")
    w("cross-checking against the transaction record, which is the layer a document-only tool")
    w("does not have.\n")

    w("### Generalisation to an unseen fake family\n")
    w("Train on three fake families, test on the fourth the model has never seen.\n")
    w("| Held out of training | Recall | FPR | PR-AUC | n |")
    w("|---|---|---|---|---|")
    for fam, r in b["leave_one_family_out"].items():
        w(f"| `{fam}` | {pct(r['recall'])} | {pct(r['fpr'])} | {r['pr_auc']:.3f} | {r['n']} |")
    w("")
    weak = min(b["leave_one_family_out"].items(), key=lambda kv: kv[1]["recall"])
    w(f"**The weak spot is `{weak[0]}` at {pct(weak[1]['recall'])} recall when unseen.** A small,")
    w("localised splice looks nothing like a wholly generated document or a recycled photograph,")
    w("so the other families teach the model little about it. Reported rather than averaged away.\n")

    w("### Ablations — what survives an adaptive forger\n")
    w("| Feature groups kept | Features | Recall | Precision | PR-AUC |")
    w("|---|---|---|---|---|")
    for k, r in b["ablations"].items():
        w(f"| `{k}` | {r['n_features']} | {pct(r['recall'])} | {pct(r['precision'])} | {r['pr_auc']:.3f} |")
    w("")
    w("Stripping EXIF is one command, so `no_provenance` is the floor a merchant should plan")
    w("around. Removing the ledger cross-check costs the most — that layer requires owning the")
    w("transaction record.\n")

    w("### Which layer carries the result\n")
    w("| Layer | Recall | Precision | FPR | F1 |")
    w("|---|---|---|---|---|")
    for k, r in b["layers"].items():
        w(f"| `{k}` | {pct(r['recall'])} | {pct(r['precision'])} | {pct(r['fpr'])} | {pct(r['f1'])} |")
    w("")
    w("### Feature-group importance\n")
    w("| Group | Importance |")
    w("|---|---|")
    for g, v in sorted(b["importance_by_group"].items(), key=lambda kv: -kv[1]):
        w(f"| `{g}` | {v} |")
    w("")
    w("`provenance` sits at zero by design. An earlier corpus gave every genuine receipt camera")
    w("EXIF and every fake none, so `exif_present` separated the classes perfectly and every")
    w("other group fell to zero importance — a detector that would have collapsed the first time")
    w("a forger ran exiftool. Modelling how evidence actually arrives (WhatsApp strips metadata;")
    w("forgers fabricate it) removed the shortcut and forced the model onto real document")
    w("features.\n")
    w("---\n")

    # ---------------- Side A ----------------
    w("## Side A — CE 3.0 qualification and win probability\n")
    w("The qualification gate is a **rulebook, not a model**: it is exact, and its correctness is")
    w("a matter of reading the Visa criteria properly rather than of accuracy. What is modelled")
    w("is the win probability conditional on qualification.\n")
    w("| Metric | Value |")
    w("|---|---|")
    w(f"| Test cases | {a['n_test']} (unseen customers) |")
    w(f"| Base rate | {pct(a['test_base_rate'])} |")
    w(f"| ROC-AUC | {a['roc_auc']:.3f} |")
    w(f"| PR-AUC | {a['pr_auc']:.3f} |")
    w(f"| Brier, uncalibrated | {a['brier_uncalibrated']:.4f} |")
    w(f"| Brier, isotonic-calibrated | {a['brier_calibrated']:.4f} |")
    w("")
    lift = a["pr_auc"] / a["test_base_rate"]
    w(f"PR-AUC {a['pr_auc']:.3f} against a base rate of {pct(a['test_base_rate'])} is roughly a")
    w(f"**{lift:.1f}× lift**. It is not higher because the generative process carries a hidden")
    w("per-issuer effect and a large noise term that no model can see — deliberately, so the")
    w("number reflects a hard problem rather than an invertible formula.\n")

    bq = a.get("by_qualification", {})
    if bq.get("qualified", {}).get("actual_win_rate") is not None:
        w("| Segment | n | Actual win rate | Mean predicted |")
        w("|---|---|---|---|")
        for k in ("qualified", "not_qualified"):
            s = bq.get(k, {})
            if s.get("actual_win_rate") is not None:
                w(f"| `{k}` | {s['n']} | {pct(s['actual_win_rate'])} | {pct(s['mean_predicted'])} |")
        w("")
    w("---\n")

    # ---------------- Fusion ----------------
    w("## M3 — Genuine-intent classifier\n")
    w(f"Test cases: {f['n_test']}. Macro F1 **{f['macro_f1']:.3f}**, accuracy {pct(f['accuracy'])},")
    w(f"log-loss {f['log_loss']:.4f}.\n")
    w("| Intent | Precision | Recall | F1 | OvR ROC-AUC | Base rate |")
    w("|---|---|---|---|---|---|")
    for k, r in f["per_class"].items():
        w(f"| `{k}` | {r['precision']:.3f} | {r['recall']:.3f} | {r['f1-score']:.3f} | "
          f"{f['ovr_roc_auc'].get(k, float('nan')):.3f} | {pct(f['base_rates'][k])} |")
    w("")
    w("Trained with balanced class weights. Unweighted, `criminal_fraud` scored **0.000 precision")
    w("and recall** — the model ranked it at 0.72 ROC-AUC but the majority classes always won the")
    w("argmax. The costs are not symmetric: predicting first-party misuse for a cardholder whose")
    w("card was genuinely stolen means pursuing a fraud victim. Accuracy fell from 0.665;")
    w(f"macro F1 rose to {f['macro_f1']:.3f}.\n")
    w("This model also consumes Side B's **out-of-fold** tamper score. Using in-sample forensic")
    w("scores would have made the feature sharper here than it can ever be in production; see")
    w("`scripts/score_evidence_oof.py`.\n")
    w("---\n")

    w("## Cost, not accuracy\n")
    w("No threshold in this system is chosen by F1. The Cost Lab sweeps policies against the")
    w("held-out set in rupees and reports the confusion matrix in rupees, because the cost of a")
    w("false positive here is a real fight fee spent on a case that loses. See the Cost Lab page")
    w("in the console for the live sweep against your own economics.\n")

    (DOCS / "METRICS.md").write_text("\n".join(L) + "\n")
    print(f"wrote {DOCS / 'METRICS.md'} ({len(L)} lines)")


if __name__ == "__main__":
    main()
